SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE MEMBER_PASSWORD;
DROP TABLE MEMBER_RELATIONS;
DROP TABLE TWEET_HISTORY;
DROP TABLE MEMBER;




/* Create Tables */

CREATE TABLE MEMBER
(
	MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '会員ID : 会員のID',
	FIRST_NAME VARCHAR(30) NOT NULL COMMENT '名',
	LAST_NAME VARCHAR(30) NOT NULL COMMENT '姓',
	NICK_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT 'ニックネーム',
	MAIL_ADDRESS VARCHAR(250) NOT NULL UNIQUE COMMENT 'メールアドレス',
	DEL_FLG CHAR(1) NOT NULL COMMENT '削除フラグ : Y:削除済み (yes)
N:未削除 (no)',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員情報';


CREATE TABLE MEMBER_PASSWORD
(
	MEMBER_ID BIGINT NOT NULL COMMENT '会員ID : 会員のID',
	PASSWORD VARCHAR(30) NOT NULL COMMENT 'パスワード',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = 'メンバーパスワード';


CREATE TABLE MEMBER_RELATIONS
(
	RELATIONS_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '関係性ID',
	FOLLOW_MEMBER_ID BIGINT NOT NULL COMMENT 'フォローメンバーID : 会員のID',
	FOLLOWER_MEMBER_ID BIGINT NOT NULL COMMENT 'フォロワーメンバーID : 会員のID',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (RELATIONS_ID),
	CONSTRAINT UQ_RELATIONS UNIQUE (FOLLOW_MEMBER_ID, FOLLOWER_MEMBER_ID)
) COMMENT = 'メンバー関係性';


CREATE TABLE TWEET_HISTORY
(
	TWEET_HISTORY_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ツイートID',
	MEMBER_ID BIGINT NOT NULL COMMENT '会員ID : 会員のID',
	TWEET VARCHAR(250) NOT NULL COMMENT 'ツイート内容',
	DEL_FLG CHAR(1) NOT NULL COMMENT 'DEL_FLG : Y:削除済み(yes)
N:未削除(no)',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (TWEET_HISTORY_ID)
) COMMENT = 'ツイート履歴';



/* Create Foreign Keys */

ALTER TABLE MEMBER_PASSWORD
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_RELATIONS
	ADD FOREIGN KEY (FOLLOW_MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MEMBER_RELATIONS
	ADD FOREIGN KEY (FOLLOWER_MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEET_HISTORY
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



