SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE MEMBER_PASSWORD;
DROP TABLE MEMBER;




/* Create Tables */

CREATE TABLE MEMBER
(
	MEMBER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT '会員ID : 会員のID',
	FIRST_NAME VARCHAR(30) NOT NULL COMMENT '名',
	LAST_NAME VARCHAR(30) NOT NULL COMMENT '姓',
	NICK_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT 'ニックネーム',
	MAIL_ADDRESS VARCHAR(250) NOT NULL UNIQUE COMMENT 'メールアドレス',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = '会員情報';


CREATE TABLE MEMBER_PASSWORD
(
	MEMBER_ID BIGINT NOT NULL COMMENT '会員ID : 会員のID',
	PASSWORD VARCHAR(30) NOT NULL COMMENT 'パスワード',
	REGISTER_TIME DATETIME NOT NULL COMMENT '作成日時',
	UPDATE_TIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO BIGINT NOT NULL COMMENT 'バージョン番号',
	PRIMARY KEY (MEMBER_ID)
) COMMENT = 'メンバーパスワード';



/* Create Foreign Keys */

ALTER TABLE MEMBER_PASSWORD
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



